# Generated by Django 4.2.7 on 2025-08-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kachel1_auftragsverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunde_title', models.CharField(help_text='Vom Kunden vorgegebener Titel - NICHT generieren!', max_length=200)),
                ('research_data', models.JSONField(default=dict, help_text='Research-Daten von Serper API')),
                ('content', models.TextField(help_text='Generierter Script-Inhalt')),
                ('week_number', models.IntegerField(help_text='Wochennummer für Organisation')),
                ('kunde_briefing', models.TextField(blank=True, help_text='Briefing vom Kunden')),
                ('kunde_keywords', models.TextField(blank=True, help_text='Keywords vom Kunden')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('serper_api_calls', models.IntegerField(default=0, help_text='Anzahl Serper API Aufrufe')),
                ('serper_kosten', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('script_status', models.CharField(choices=[('RESEARCH', 'Research Phase'), ('DRAFT', 'Entwurf'), ('REVIEW', 'Review'), ('FINAL', 'Final'), ('DELIVERED', 'Ausgeliefert')], default='RESEARCH', max_length=20)),
                ('auftrag', models.ForeignKey(limit_choices_to={'status': 'AKTIV'}, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='kachel1_auftragsverwaltung.auftrag')),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
                'ordering': ['-week_number', '-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Arbeitsprobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_title', models.CharField(help_text='Automatisch generierter Titel für die Arbeitsprobe', max_length=200)),
                ('content', models.TextField(help_text='Generierter Inhalt der Arbeitsprobe')),
                ('quality', models.CharField(choices=[('bronze', 'Bronze ($0.35)'), ('silber', 'Silber ($0.63)'), ('gold', 'Gold ($0.93)')], help_text='Qualitätsstufe bestimmt API-Kosten', max_length=10)),
                ('upwork_job_url', models.URLField(blank=True, null=True)),
                ('upwork_job_description', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('api_kosten', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('auftrag', models.ForeignKey(limit_choices_to={'status': 'OFFEN'}, on_delete=django.db.models.deletion.CASCADE, related_name='arbeitsproben', to='kachel1_auftragsverwaltung.auftrag')),
            ],
            options={
                'verbose_name': 'Arbeitsprobe',
                'verbose_name_plural': 'Arbeitsproben',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
