# Generated by Django 4.2.7 on 2025-08-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auftrag',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField()),
                ('status', models.CharField(choices=[('OFFEN', 'Offen'), ('AKTIV', 'Aktiv'), ('ABGESCHLOSSEN', 'Abgeschlossen'), ('ABGESAGT', 'Abgesagt')], default='OFFEN', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('woche', models.IntegerField(blank=True, help_text='Wochennummer für Organisation', null=True)),
                ('prioritaet', models.CharField(choices=[('NIEDRIG', 'Niedrig'), ('MITTEL', 'Mittel'), ('HOCH', 'Hoch')], default='MITTEL', max_length=10)),
            ],
            options={
                'verbose_name': 'Auftrag',
                'verbose_name_plural': 'Aufträge',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
